# Setup
title:        Pragmatic Ways
tagline:      Finding the practical ways of success. 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Adam Allard
  url:        http://pragmaticways.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
