# Site settings
title: Pragmatic Blog
header-img: img/home-bg.jpg
email: adam@pragmaticways.com
copyright_name: Pragmatic Ways
description: "Finding the practical ways of success."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Adam_Allard_
github_username:  amallard
facebook_username:  adam.allard.codes
email_username:  adam.allard@live.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
